# Generated by Django 2.1.5 on 2019-03-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestversion',
            name='docVersionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Documents'),
        ),
    ]
