# Generated by Django 2.1.5 on 2019-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0002_auto_20190321_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='lock',
            field=models.IntegerField(default=0),
        ),
    ]
