# Generated by Django 2.1.5 on 2019-04-12 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0003_auto_20190327_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.IntegerField()),
                ('reject', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('docID', models.DateTimeField()),
                ('commentID', models.AutoField(primary_key=True, serialize=False, verbose_name='Comment ID')),
                ('version', models.FloatField()),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(default=datetime.datetime(2019, 4, 12, 18, 20, 2, 250789))),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyID', models.AutoField(primary_key=True, serialize=False, verbose_name='Reply ID')),
                ('reply', models.TextField()),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Comments')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users')),
            ],
        ),
        migrations.AddField(
            model_name='accept_reject',
            name='commentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Comments'),
        ),
        migrations.AddField(
            model_name='accept_reject',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users'),
        ),
    ]
