# Generated by Django 2.1.5 on 2019-04-15 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0006_auto_20190416_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestversion',
            name='lockUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 3, 10, 49, 415927)),
        ),
    ]
